// GENERAL UI
export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
// AUTH
export const SET_CURRENT_USER = "SET_CURRENT_USER";
// FILE UPLOAD
export const UPLOAD_START = "UPLOAD_START";
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_FAIL = "UPLOAD_FAIL";
// MATERIALS
export const GET_MATERIALS_SUCCESS = "GET_MATERIALS_SUCCESS";
export const UNLOAD_MATERIALS = "UNLOAD_MATERIALS";
export const UPDATE_MATERIAL = "UPDATE_MATERIAL";
// BLOG/ARTICLES
export const INITIALIZE_BLOG = "INITIALIZE_BLOG";
export const UNLOAD_BLOG = "UNLOAD_BLOG";
export const RETRIEVE_ARTICLE = "RETRIEVE_ARTICLE";
export const UNLOAD_ARTICLE = "UNLOAD_ARTICLE";
// SEARCH
export const HANDLE_SEARCH = "HANDLE_SEARCH";
// ADMIN
export const INITIALIZE_LIST = "INITIALIZE_LIST";
export const UNLOAD_LIST = "UNLOAD_LIST";
export const INITIALIZE_COMMENT = "INITIALIZE_COMMENT";
export const UNLOAD_COMMENT = "UNLOAD_COMMENT";
export const INITIALIZE_MATERIAL = "INITIALIZE_MATERIAL";
export const UNLOAD_MATERIAL = "UNLOAD_MATERIAL";